### ISSUE TITLE
MSDformer中的一个问题点

### ISSUE THREAD

**Issue by 1273974861** [Tomchenshi/MSDformer#3]
在MSDformer模型中，MSAM模块中前驱函数处是否有点错误，在用全零张量y来存储处理后的各个通道时，最后对重叠部分取平均那里应当将y与xi的直接赋值改为累加把
![Uploading 问题图片.png…]()

**Comment by 1273974861** [comment]
在这里：         
  # 运算结果存储下来，感觉为了匹配满足下文这里应处理为 y[:, sta_ind:end_ind, :, :] += xi
            y[:, sta_ind:end_ind, :, :] = xi

**Comment by Tomchenshi** [comment]
您好，感谢您的宝贵意见，已经在代码中进行修改

**Comment by 1273974861** [comment]
大佬，请问能获取下你的联系方式吗，代码运行上有些问题想问问，我的邮箱是1273974861@qq.com希望可以得到您的回复
